# Generated by Django 4.2.7 on 2025-11-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('package_type', models.CharField(blank=True, max_length=100)),
                ('package_description', models.TextField(blank=True)),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('expected_arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_city', models.CharField(blank=True, max_length=100)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.TextField(blank=True)),
                ('transit_point', models.CharField(blank=True, max_length=100)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('shipper_full_name', models.CharField(blank=True, max_length=200)),
                ('shipper_email', models.EmailField(blank=True, max_length=254)),
                ('shipper_country', models.CharField(blank=True, max_length=100)),
                ('shipper_city', models.CharField(blank=True, max_length=100)),
                ('shipper_address', models.TextField(blank=True)),
                ('receiver_full_name', models.CharField(blank=True, max_length=200)),
                ('receiver_email', models.EmailField(blank=True, max_length=254)),
                ('receiver_country', models.CharField(blank=True, max_length=100)),
                ('receiver_city', models.CharField(blank=True, max_length=100)),
                ('receiver_address', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipment_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('shipment_progress', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shipment_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.shipment')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
