# Generated by Django 4.2.7 on 2025-12-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_progress',
        ),
    ]
