# Generated by Django 4.2.7 on 2025-12-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_shipment_shipment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_progress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
